services:
  web:
    build:
      context: ./mydocs
      dockerfile: Dockerfile
    image: web
    ports:
      - "3000:5173"
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
