services:
  web:
    build:
      context: ./mydocs
      dockerfile: Dockerfile
    image: web
    ports:
      - "3000:5173"
    depends_on:
      - api
    networks:
      - application

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - application

  db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - application
    volumes:
      - mongodb_data:/data/db

networks:
  application:
    driver: bridge

volumes:
  mongodb_data:
